{{- range $component := list "backend" "frontend" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $component }}
  labels: {app: {{ $.Release.Name }}, component: {{ $component }}}
spec:
  type: ClusterIP
  selector: {app: {{ $.Release.Name }}, component: {{ $component }}}
  ports:
    - name: http
      port: {{ if eq $component "frontend" }}3100{{ else }}8000{{ end }}
      targetPort: {{ if eq $component "frontend" }}3100{{ else }}8000{{ end }}
---
{{- end }}
